# Generated by Django 5.2.6 on 2025-11-17 23:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_user_fk_devicepairingsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.CharField(help_text='Base64-encoded WebAuthn credential ID used for this approval', max_length=512, verbose_name='Credential ID')),
                ('challenge_id', models.CharField(help_text='Unique identifier for the challenge', max_length=128, verbose_name='Challenge ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], help_text='Type of approval action', max_length=20, verbose_name='Action')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='success', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context: approval amount, type, etc.', verbose_name='Context Data')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Performed At')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Approval Audit',
                'verbose_name_plural': 'Approval Audits',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='webauthn_last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last WebAuthn Login'),
        ),
    ]
