# Generated by Django 5.2.6 on 2025-11-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_approvalaudit_user_webauthn_last_login_at'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalaudit',
            name='approval_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_audits', to='requests.approvalrequest', verbose_name='Approval Request'),
        ),
        migrations.AddField(
            model_name='approvalaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_audits', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='approvalaudit',
            index=models.Index(fields=['approval_request', 'performed_at'], name='authenticat_approva_42b466_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaudit',
            index=models.Index(fields=['user', 'performed_at'], name='authenticat_user_id_b49435_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaudit',
            index=models.Index(fields=['status'], name='authenticat_status_b51cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalaudit',
            index=models.Index(fields=['credential_id'], name='authenticat_credent_d985cc_idx'),
        ),
    ]
