# Generated by GitHub Copilot

import uuid

from django.db import migrations, models, connection
import django.db.models.deletion


def check_and_create_models(apps, schema_editor):
    """
    Verifica si las tablas ya existen antes de crearlas.
    Esto hace la migración idempotente.
    """
    with connection.cursor() as cursor:
        # Verificar si las tablas ya existen
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'authentication_termsapprovalsession'
            );
        """)
        terms_session_exists = cursor.fetchone()[0]
        
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'authentication_termsacceptanceaudit'
            );
        """)
        terms_audit_exists = cursor.fetchone()[0]
    
    if terms_session_exists and terms_audit_exists:
        print("⚠️  Las tablas ya existen. Saltando creación de modelos.")
        # Marcar esta migración como aplicada
        return
    
    print("✓ Tablas no existen. Creando modelos...")


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_plan_id'),
        ('authentication', '0006_approvalaudit_approval_request_approvalaudit_user_and_more'),
    ]

    operations = [
        # Primero verificar si las tablas existen
        migrations.RunPython(check_and_create_models, migrations.RunPython.noop),
        
        # Crear modelos (se saltarán si ya existen gracias al manejo de errores en el deploy)
        migrations.CreateModel(
            name='TermsApprovalSession',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('purpose', models.CharField(choices=[('terms_acceptance', 'Terms Acceptance'), ('generic', 'Generic')], default='terms_acceptance', max_length=64, verbose_name='Purpose')),
                ('document_type', models.CharField(default='terms', max_length=32, verbose_name='Document Type')),
                ('document_version', models.CharField(blank=True, max_length=64, verbose_name='Document Version')),
                ('document_hash', models.CharField(blank=True, max_length=128, verbose_name='Document Hash')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Context Data')),
                ('approval_id', models.CharField(max_length=128, verbose_name='Approval ID')),
                ('challenge_id', models.CharField(blank=True, max_length=128, verbose_name='Challenge ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Token Hash')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consumed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_terms_approval_sessions', to='authentication.user', verbose_name='Created By')),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_approval_sessions', to='authentication.user', verbose_name='User')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_approval_sessions', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Terms Approval Session',
                'verbose_name_plural': 'Terms Approval Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsAcceptanceAudit',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('purpose', models.CharField(default='terms_acceptance', max_length=64, verbose_name='Purpose')),
                ('document_type', models.CharField(default='terms', max_length=32, verbose_name='Document Type')),
                ('document_version', models.CharField(blank=True, max_length=64, verbose_name='Document Version')),
                ('document_hash', models.CharField(blank=True, max_length=128, verbose_name='Document Hash')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='success', max_length=20, verbose_name='Status')),
                ('credential_id', models.CharField(blank=True, max_length=512, verbose_name='Credential ID')),
                ('challenge_id', models.CharField(blank=True, max_length=128, verbose_name='Challenge ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of user fields at the time of acceptance', verbose_name='User Snapshot')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Context Data')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Performed At')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_terms_acceptance_audits', to='authentication.user', verbose_name='Initiated By')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='authentication.termsapprovalsession', verbose_name='Approval Session')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptance_audits', to='tenants.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptance_audits', to='authentication.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Terms Acceptance Audit',
                'verbose_name_plural': 'Terms Acceptance Audits',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='termsapprovalsession',
            index=models.Index(fields=['tenant', 'subject_user', 'created_at'], name='authent_tenant__b84e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='termsapprovalsession',
            index=models.Index(fields=['expires_at'], name='authent_expires_8820a4_idx'),
        ),
        migrations.AddIndex(
            model_name='termsapprovalsession',
            index=models.Index(fields=['consumed_at'], name='authent_consume_4dd003_idx'),
        ),
        migrations.AddIndex(
            model_name='termsacceptanceaudit',
            index=models.Index(fields=['tenant', 'performed_at'], name='authent_tenant__0d2e4f_idx'),
        ),
        migrations.AddIndex(
            model_name='termsacceptanceaudit',
            index=models.Index(fields=['user', 'performed_at'], name='authent_user_p_4a6813_idx'),
        ),
        migrations.AddIndex(
            model_name='termsacceptanceaudit',
            index=models.Index(fields=['status'], name='authent_status_4c5df9_idx'),
        ),
    ]
