# Generated by Django 4.2.7 on 2026-01-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_terms_approval_session_and_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='termsacceptanceaudit',
            new_name='authenticat_tenant__f31d57_idx',
            old_name='authent_tenant__0d2e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='termsacceptanceaudit',
            new_name='authenticat_user_id_5d59ec_idx',
            old_name='authent_user_p_4a6813_idx',
        ),
        migrations.RenameIndex(
            model_name='termsacceptanceaudit',
            new_name='authenticat_status_fed9a2_idx',
            old_name='authent_status_4c5df9_idx',
        ),
        migrations.RenameIndex(
            model_name='termsapprovalsession',
            new_name='authenticat_tenant__1177fb_idx',
            old_name='authent_tenant__b84e0d_idx',
        ),
        migrations.RenameIndex(
            model_name='termsapprovalsession',
            new_name='authenticat_expires_73e692_idx',
            old_name='authent_expires_8820a4_idx',
        ),
        migrations.RenameIndex(
            model_name='termsapprovalsession',
            new_name='authenticat_consume_e2ca42_idx',
            old_name='authent_consume_4dd003_idx',
        ),
    ]
