# Generated by Django 4.2.7 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_authent_tenant__0d2e4f_idx_authenticat_tenant__f31d57_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsapprovalsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='termsapprovalsession',
            name='decision',
            field=models.CharField(
                choices=[('approve', 'Approve'), ('reject', 'Reject')],
                default='approve',
                max_length=16,
                verbose_name='Decision',
            ),
        ),
        migrations.AddField(
            model_name='termsapprovalsession',
            name='parent_origin',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Exact top-level origin authorized to host this WebAuthn ceremony',
                max_length=255,
                verbose_name='Parent Origin',
            ),
        ),
        migrations.AddField(
            model_name='termsapprovalsession',
            name='result_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('failed', 'Failed'),
                    ('expired', 'Expired'),
                ],
                default='pending',
                max_length=20,
                verbose_name='Result Status',
            ),
        ),
        migrations.AddIndex(
            model_name='termsapprovalsession',
            index=models.Index(fields=['result_status'], name='authenticat_result__a421b5_idx'),
        ),
    ]
