# Prometheus Alert Rules for SecureApprove

groups:
  - name: api_alerts
    interval: 30s
    rules:
      # API Instance Down
      - alert: APIInstanceDown
        expr: up{job="api"} == 0
        for: 1m
        labels:
          severity: critical
          component: api
        annotations:
          summary: "API instance {{ $labels.instance }} is down"
          description: "API instance {{ $labels.instance }} has been down for more than 1 minute."

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        labels:
          severity: high
          component: api
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.instance }}"

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 450
        for: 5m
        labels:
          severity: warning
          component: api
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}MB for {{ $labels.instance }}"

      # Too Many Requests
      - alert: RateLimitExceeded
        expr: rate(rate_limit_exceeded_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          component: security
        annotations:
          summary: "Rate limit frequently exceeded"
          description: "Rate limit exceeded {{ $value }} times/sec for {{ $labels.instance }}"

  - name: database_alerts
    interval: 30s
    rules:
      # MongoDB Primary Down
      - alert: MongoDBPrimaryDown
        expr: mongodb_up{instance="mongodb-primary"} == 0
        for: 1m
        labels:
          severity: critical
          component: database
        annotations:
          summary: "MongoDB primary is down"
          description: "MongoDB primary instance has been down for more than 1 minute."

      # MongoDB Replication Lag
      - alert: MongoDBReplicationLag
        expr: mongodb_replset_member_replication_lag > 10
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "MongoDB replication lag detected"
          description: "Replication lag is {{ $value }}s for {{ $labels.instance }}"

      # MongoDB Connection Pool Exhausted
      - alert: MongoDBConnectionPoolExhausted
        expr: mongodb_connections_current / mongodb_connections_available > 0.9
        for: 5m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "MongoDB connection pool almost exhausted"
          description: "Connection pool usage is {{ $value | humanizePercentage }}"

      # Redis Master Down
      - alert: RedisMasterDown
        expr: redis_up{role="master"} == 0
        for: 1m
        labels:
          severity: critical
          component: cache
        annotations:
          summary: "Redis master is down"
          description: "Redis master has been down for more than 1 minute."

      # Redis High Memory Usage
      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          component: cache
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

  - name: security_alerts
    interval: 30s
    rules:
      # Failed Authentication Attempts
      - alert: HighFailedAuthAttempts
        expr: rate(auth_failed_total[5m]) > 10
        for: 5m
        labels:
          severity: high
          component: security
        annotations:
          summary: "High number of failed authentication attempts"
          description: "{{ $value }} failed auth attempts per second from {{ $labels.ip }}"

      # Suspicious Activity
      - alert: SuspiciousActivity
        expr: rate(security_alert_total[5m]) > 5
        for: 5m
        labels:
          severity: high
          component: security
        annotations:
          summary: "Suspicious activity detected"
          description: "{{ $value }} security alerts per second"

      # SSL Certificate Expiry
      - alert: SSLCertificateExpiringSoon
        expr: (ssl_certificate_expiry_timestamp - time()) / 86400 < 7
        for: 1h
        labels:
          severity: warning
          component: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.domain }} expires in {{ $value }} days"

  - name: system_alerts
    interval: 30s
    rules:
      # High CPU Usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      # High Disk Usage
      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      # Container Restart
      - alert: ContainerRestarted
        expr: rate(container_restart_count[15m]) > 0
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "Container restarted"
          description: "Container {{ $labels.container }} has restarted {{ $value }} times"

  - name: business_alerts
    interval: 1m
    rules:
      # Low Approval Rate
      - alert: LowApprovalRate
        expr: rate(approval_approved_total[1h]) / rate(approval_total[1h]) < 0.5
        for: 30m
        labels:
          severity: info
          component: business
        annotations:
          summary: "Low approval rate detected"
          description: "Approval rate is {{ $value | humanizePercentage }} in the last hour"

      # Unusual User Activity
      - alert: UnusualUserActivity
        expr: rate(user_actions_total[5m]) > 2 * avg_over_time(rate(user_actions_total[5m])[1h:5m])
        for: 10m
        labels:
          severity: info
          component: business
        annotations:
          summary: "Unusual user activity detected"
          description: "User activity is {{ $value }}x above normal for {{ $labels.user }}"
