# Generated by Django 4.2.7 on 2025-11-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale'), ('tier_1', 'Small Team'), ('tier_2', 'Medium Team'), ('tier_3', 'Large Team')], max_length=100, unique=True),
        ),
    ]
