# Generated by Django 5.2.6 on 2025-11-17 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('expense', 'Expense Reimbursement'), ('purchase', 'Purchase Request'), ('travel', 'Travel Approval'), ('contract', 'Contract Approval'), ('document', 'Document Withdrawal'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount for expense, purchase, or travel requests', max_digits=10, null=True, verbose_name='Amount')),
                ('approver_comment', models.TextField(blank=True, verbose_name='Approver Comment')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Category-specific data: vendor, cost_center, destination, etc.', verbose_name='Metadata')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approver')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='requests_ap_tenant__fa85ec_idx'), models.Index(fields=['requester', 'created_at'], name='requests_ap_request_917af0_idx'), models.Index(fields=['approver', 'approved_at'], name='requests_ap_approve_7dc625_idx'), models.Index(fields=['status', 'priority'], name='requests_ap_status_9583aa_idx')],
            },
        ),
    ]
