# Generated by Django 5.2.6 on 2025-11-18 11:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_approvalaudit_approval_request_approvalaudit_user_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chat_presence', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last Activity')),
                ('is_online', models.BooleanField(default=False, help_text='Computed field: online if last_activity is recent', verbose_name='Is Online')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Presence',
                'verbose_name_plural': 'User Presences',
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional title for group conversations', max_length=255, verbose_name='Title')),
                ('is_group', models.BooleanField(default=False, help_text='True for group conversations, False for 1-to-1', verbose_name='Is Group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Chat Conversation',
                'verbose_name_plural': 'Chat Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, help_text='Message text content', max_length=5000, verbose_name='Content')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='Has Attachments')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', help_text='Aggregated delivery status', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='last_message',
            field=models.ForeignKey(blank=True, help_text='Cache of last message for quick access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chatmessage'),
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='chat_attachments/%Y/%m/', verbose_name='File')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='Filename')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content Type')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Size (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage')),
            ],
            options={
                'verbose_name': 'Chat Attachment',
                'verbose_name_plural': 'Chat Attachments',
            },
        ),
        migrations.CreateModel(
            name='ChatMessageDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='chat.chatmessage')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message Delivery',
                'verbose_name_plural': 'Chat Message Deliveries',
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unread_count', models.PositiveIntegerField(default=0, help_text='Cached count of unread messages', verbose_name='Unread Count')),
                ('is_archived', models.BooleanField(default=False, help_text='User has archived this conversation', verbose_name='Is Archived')),
                ('is_muted', models.BooleanField(default=False, help_text='User has muted notifications for this conversation', verbose_name='Is Muted')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_set', to='chat.chatconversation')),
                ('last_read_message', models.ForeignKey(blank=True, help_text='Last message this user has read', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participant_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
            },
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='participants',
            field=models.ManyToManyField(related_name='chat_conversations', through='chat.ChatParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_chatme_convers_c2caf0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-created_at'], name='chat_chatme_sender__8c4a71_idx'),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='chat_chatat_message_325564_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessagedelivery',
            index=models.Index(fields=['recipient', 'read_at'], name='chat_chatme_recipie_23a6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessagedelivery',
            index=models.Index(fields=['message', 'recipient'], name='chat_chatme_message_1960fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmessagedelivery',
            unique_together={('message', 'recipient')},
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', '-joined_at'], name='chat_chatpa_user_id_7d4cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['conversation', 'user'], name='chat_chatpa_convers_6424b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('conversation', 'user')},
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['tenant', '-updated_at'], name='chat_chatco_tenant__5fcd20_idx'),
        ),
    ]
