# Generated by Django 5.2.6 on 2025-11-16 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Key')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('plan_id', models.CharField(choices=[('starter', 'Starter - Up to 2 approvers'), ('growth', 'Growth - Up to 6 approvers'), ('scale', 'Scale - Unlimited approvers')], default='starter', max_length=20, verbose_name='Plan')),
                ('seats', models.PositiveIntegerField(default=5, verbose_name='Seats')),
                ('approver_limit', models.PositiveIntegerField(default=2, verbose_name='Approver Limit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('trial', 'Trial')], default='trial', max_length=20, verbose_name='Status')),
                ('billing', models.JSONField(blank=True, default=dict, help_text='Stores billing provider data, subscription IDs, etc.', verbose_name='Billing Information')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional tenant configuration and data', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantUserInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(default='requester', max_length=20, verbose_name='Role')),
                ('token', models.CharField(max_length=128, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Tenant User Invite',
                'verbose_name_plural': 'Tenant User Invites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'email'], name='tenants_ten_tenant__792782_idx'), models.Index(fields=['tenant', 'status'], name='tenants_ten_tenant__c89ea4_idx')],
            },
        ),
    ]
