# Generated by Django 5.2.6 on 2025-12-05 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTypeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_key', models.CharField(help_text='Unique identifier for this approval type within the tenant', max_length=50, verbose_name='Category Key')),
                ('name', models.CharField(help_text='Display name for this approval type', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of this approval type', verbose_name='Description')),
                ('icon', models.CharField(default='bi-file-earmark-check', help_text='Bootstrap Icons class (e.g., bi-cash, bi-cart)', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class (primary, success, warning, danger, info)', max_length=20, verbose_name='Color')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this approval type is available for new requests', verbose_name='Enabled')),
                ('is_custom', models.BooleanField(default=False, help_text='True if this is a custom type created by the tenant', verbose_name='Custom Type')),
                ('required_approvers', models.PositiveIntegerField(default=1, help_text='Number of approvers required to approve requests of this type', verbose_name='Required Approvers')),
                ('show_amount', models.BooleanField(default=False, help_text='Whether to show the amount field for this approval type', verbose_name='Show Amount Field')),
                ('extra_fields', models.JSONField(blank=True, default=list, help_text='Additional fields configuration for this approval type', verbose_name='Extra Fields')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order in which this type appears in lists', verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('designated_approvers', models.ManyToManyField(blank=True, help_text='Specific users who can approve this type. Leave empty for any approver.', related_name='designated_approval_types', to=settings.AUTH_USER_MODEL, verbose_name='Designated Approvers')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_type_configs', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Approval Type Configuration',
                'verbose_name_plural': 'Approval Type Configurations',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_enabled'], name='tenants_app_tenant__0d9553_idx'), models.Index(fields=['tenant', 'category_key'], name='tenants_app_tenant__f2e9a1_idx')],
                'unique_together': {('tenant', 'category_key')},
            },
        ),
    ]
