# Generated by Django 4.2.7 on 2025-12-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_add_approval_type_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='plan_id',
            field=models.CharField(choices=[('tier_1', '2-6 users - $60/user/month'), ('tier_2', '7-12 users - $55/user/month'), ('tier_3', '12+ users - $50/user/month')], default='tier_1', max_length=20, verbose_name='Plan'),
        ),
    ]
